language: java
jdk:
  - oraclejdk9
before_install:
  - cd library
  - chmod +x gradlew
before_deploy:
  - ./gradlew generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    branch: fix_gradle
