language: java
jdk:
  - oraclejdk9
before_install:
  - cd library
  - chmod +x gradlew
  - cd src/frontend
  - npm install
  - npm run build
  - cd ../..
before_deploy:
  - ./gradlew generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    all_branches: true
