language: java
jdk:
  - oraclejdk9
before_install:
  - cd library
  - chmod +x gradlew
  - cd src/frontend
  - npm install
  - npm run build
  - cd ../..
deploy:
  -
    provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      branch: release
  -
    provider: script
    script: ./gradlew artifactoryPublish -Dsnapshot=true
    skip_cleanup: true
    on:
      branch: master
