language: java
jdk:
  - oraclejdk9
before_install:
  - cd library
  - chmod +x gradlew
  - cd src/frontend
  - npm install
  - npm run build
  - cd ../..
  - if [ "$TRAVIS_BRANCH" = "master" ]; then eval export SNAPSHOT=true; fi
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: ci_snapshot_release
